In [1]:
import numpy as np
import math


In [12]:
sweep = [
    [0.0, 0.0],
    [0.3, 0.0005],
    [0.7812, 0.00119],
    [1.1718, 0.00179],
]

## Math 

In [20]:
def rotateMAth(origin, point, angle):
    """
    Rotate a point counterclockwise by a given angle around a given origin.
    The angle should be given in radians.
    """
    ox, oy = origin
    px, py = point

    qx = ox + math.cos(angle) * (px - ox) - math.sin(angle) * (py - oy)
    qy = oy + math.sin(angle) * (px - ox) + math.cos(angle) * (py - oy)
    return qx, qy


In [21]:
point = (10, 0)
origin = (0, 0)
rotateMAth(origin, point, math.radians(45))
# (2.6375113976783475, 4.143263683691346)

(7.0710678118654755, 7.0710678118654755)

## Scipy

In [78]:
from scipy.ndimage import rotate

In [90]:
sweep_3d = [
    [0.3, 0.0005,0],
    [0.7812, 0.00119,0],
    [1.1718, 0.00179,0],
]

sweep = [[10,0]]

In [91]:
from scipy.spatial.transform import Rotation as R

In [92]:
p = R.from_euler("yx",sweep, degrees=True )
p.as_euler('zyx', degrees=True)

array([[ 0., 10.,  0.]])

In [102]:
#10° rotation in each principal direction:
r = R.from_euler('yx',(10,10), degrees=True) 
r

In [103]:

p_r=r.apply(p) #Rotated points

p_r

ValueError: Expected input of shape (3,) or (P, 3), got (1,).

In [38]:
rotate(sweep_3d, angle=45)


array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  5.84214963e-04, -3.52943376e-02,
         0.00000000e+00],
       [ 0.00000000e+00,  6.55195434e-01,  1.72442465e-03,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00]])

In [ ]:
np.rot

In [191]:
import numpy as np
from scipy.ndimage import rotate
x = np.array([[10,0,0], [5,0,0]])
rotate(x, angle=45, reshape=False)

array([[ 0, -1,  0],
       [ 0,  2,  0]])

## Open3D

In [192]:
import numpy as np
import open3d as o3d

In [258]:
yxz = [[0,10,0], [0,5,0]]

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(yxz)

xyz_load = np.asarray(pcd.points)
xyz_load

array([[ 0., 10.,  0.],
       [ 0.,  5.,  0.]])

In [259]:
# R = pcd.get_rotation_matrix_from_xyz((np.pi / 2, 0, np.pi / 4))
R = pcd.get_rotation_matrix_from_xyz((0, 0, math.radians(-90)))
# R = pcd.get_rotation_matrix_from_axis_angle((math.radians(45), 0, 0))

pcd=pcd.rotate(R, center=(0,0,0))

xyz_load = np.asarray(pcd.points)
xyz_load

array([[1.000000e+01, 6.123234e-16, 0.000000e+00],
       [5.000000e+00, 3.061617e-16, 0.000000e+00]])

In [262]:
def rotate_point_cloud_azimuth(pcd_yxz, degrees):
    """
    Rotate points along azimuth  
    ----------------

    pcd_yxz: Points coordinates YXZ [[y1,x1,z1],[y2,x2,z2]...]
    degrees: float 

    ### Return
    Rotated point cloud as a numpy array YXZ
    """
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(pcd_yxz)  # Array input format 
    R = pcd.get_rotation_matrix_from_xyz((0, 0, math.radians(degrees))) 
    pcd=pcd.rotate(R, center=(0,0,0))
    yxz_load = np.asarray(pcd.points)
    return yxz_load


yxz = [[0,10,0], [0,5,0]]

rotate_point_cloud_azimuth(yxz, 45)

array([[-7.07106781,  7.07106781,  0.        ],
       [-3.53553391,  3.53553391,  0.        ]])

In [144]:
o3d.visualization.draw_geometries([pcd])

In [ ]:
o3d.visualization.draw_geometries([pcd],
                                  zoom=1,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[0, 0, 0],
                                  up=[-0.0694, -0.9768, 0.2024])

In [209]:
mesh = o3d.geometry.TriangleMesh.create_coordinate_frame()
mesh_tx = copy.deepcopy(mesh).translate((1.3, 0, 0))
mesh_ty = copy.deepcopy(mesh).translate((0, 1.3, 0))
print(f'Center of mesh: {mesh.get_center()}')
print(f'Center of mesh tx: {mesh_tx.get_center()}')
print(f'Center of mesh ty: {mesh_ty.get_center()}')
o3d.visualization.draw_geometries([mesh, mesh_tx, mesh_ty])

NameError: name 'copy' is not defined

# Numpy add element to all items

In [9]:
# XY Points to XYZ Points  

points_xy = np.asarray([[1,2],[2,2]])

for k in rangepoints_xy:
    k.append(0)
    k[k] = k

points_xy

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [1]:
points = [[1,2],[2,2]]

[[x,y,0] for (x,y) in points]


[[1, 2, 0], [2, 2, 0]]

In [12]:
yxz_rotated = np.asarray(points).tolist()
yxz_rotated_str = str(yxz_rotated)
yxz_rotated_str

'[[1, 2], [2, 2]]'

In [2]:
import random

random.randint(1,999)

529